---
title: "Untitled"
---

# AI

## Vertex AI

-   구글의 '버텍스 AI(Vertex AI)'는 특성 추출부터 모델 학습과 저지연 추론에 이르기까지 데이터 과학자와 AI 개발자가 인공지능(AI) 애플리케이션을 더 쉽게 통합하고 모델의 배포 및 유지 관리를 가속화 할 수 있는 관리형 머신러닝(ML) 플랫폼으로 2021년 5월에 발표(보기)되었다

-   버텍스 AI는 필요한 모든 도구를 갖춘 단일 플랫폼으로 특별히 머신러닝 학습을 필요로 하지 않고 데이터, 프로토타입, 테스트, 모델 배치, 모델 해석 및 생산 모니터링을 할 수 있다. 즉, 기본 지식만 있으면 누구나 이 툴을 사용해 머신러닝 모델을 구현하고 배포할 수 있다.

-   https://cloud.google.com/vertex-ai/docs/model-registry/introduction?hl=ko

-   https://www.aitimes.kr/news/articleView.html?idxno=27860

-   https://bcho.tistory.com/1383

## AI 모델 레포지토리

-   구조는 그림 1과 같다. 개발자 혹은 사용자가 최적화된 AI 모델을 학습하여 다양한 모델을 생성한 다음, AI 모델 레포지토리에 등록한다. 이 때 원활한 검색을 위해 모델의 특징을 등록하는데, 제안하는 시스템에서는 이를 컨텍스트라고 정의한다. 등록된 모델은 컨텍스트를 기반으로 관리되며, 검색 조건도 컨텍스트를 활용한다. IoT 디바이스는 필요 시 AI 모델 레포지토리에서 AI 모델을 검색한 다음, 배포 기능을 이용해 모델을 다운로드받는다. 이후 선택적으로 여러 AI 모델을 활용하여 on-device AI를 수행한다.

-   참고자료: 이석준, 최충재, 성낙명.(2022).IoT 온디바이스 AI 실현을 위한 AI 모델 레포지토리.한국정보통신학회 종합학술대회 논문집,26(2),597-599.

## AI 워크벤치

-   **간소화된 모델 튜닝과 배포 도입 -** 엔비디아가 간편한 통합 툴킷인 엔비디아 AI 워크벤치(NVIDIA AI Workbench)를 발표했다. 이를 통해 개발자는 PC 또는 워크스테이션에서 사전 학습된 생성형 AI 모델을 빠르게 생성, 테스트, 맞춤화한 후 거의 모든 데이터센터, 공용 클라우드, 엔비디아 DGX 클라우드 등으로 확장할 수 있다.

-   AI 워크벤치는 기업이 AI 프로젝트를 시작할 때 겪는 복잡성을 최소화한다. 로컬 시스템에서 실행되는 간소화된 인터페이스를 통해 액세스할 수 있으며, 개발자는 맞춤형 데이터를 사용해 허깅페이스(Hugging Face), 깃허브(GitHub), 엔비디아 NGC와 같은 인기 리포지토리에서 모델을 맞춤화한 다음 여러 플랫폼에서 쉽게 공유할 수 있다.

-   엔비디아 AI 워크벤치를 사용하면 몇 번의 클릭만으로 생성형 AI를 맞춤화하고 실행할 수 있다. 이를 통해 오픈 소스 리포지토리와 엔비디아 AI 플랫폼에서 필요한 모든 엔터프라이즈급 모델, 프레임워크, 소프트웨어 개발 키트, 라이브러리를 통합된 개발자 툴킷으로 가져올 수 있다.

-   https://www.elec4.co.kr/article/articleView.asp?idx=31589

## Airflow

-   데이터 처리에 중점을 둔 저장소이다. 에어플로우는 테스크가 이상적으로 멱등성의 법칙을 따라야 한다는 철학을 갖고 개발되었다. 이를 간단히 설명하자면 목적지 시스템에서 이중 데이터가 생성되지 않으며 테스크의 결과는 언제나 같아야 한다는 것이다.

-   에어플로우는 한마디로 일련을 일들을 순차적으로 진행시켜주는 프로젝트 관리자.

-   https://lsjsj92.tistory.com/631

# 
