---
title: "Automation"
author: "Haseong"
date: "08/17/2023"
filters: 
  - lightbox
lightbox: auto
categories:
  - syntheic biology
  - automation
  - biofoundry
---

# Automation

## 논문

### Enabling high-throughput biology with flexible open-source automation

    https://www.embopress.org/doi/full/10.15252/msb.20209942
      
      복잡한 생활 시스템에 대한 우리의 이해는 높은 처리량으로 실험을 수행할 수 있는 우리의 능력에 의해 제한됩니다. 로봇 시스템은 많은 전통적인 수동 피펫팅 프로토콜을 자동화했지만 소프트웨어 제한으로 인해 수백 개의 실험을 동시에 조작, 유지 및 모니터링하는 데 필요한 고급 조작이 불가능했습니다. 여기에서는 메타 모집단 역학 시뮬레이션과 같은 사용자 지정 고처리량 실험에 필요한 복잡한 피펫팅 패턴을 실행할 수 있는 오픈 소스 Python 플랫폼인 Pyhamilton을 소개합니다. 통합 플레이트 리더를 사용하여 로봇 방법을 실시간으로 조정하기 위해 정기적인 밀도 측정을 수행함으로써 사용자 개입 없이 며칠 동안 거의 500개에 가까운 원격 모니터링 세균 배양을 대수 성장 상태로 유지합니다. 이러한 기능을 사용하여 우리는 탄소, 질소 및 인 피트니스 환경을 종합적으로 샘플링하기 위해 3중으로 100가지 연속 배양 조건의 형광 단백질 발현 및 성장률을 모니터링하여 생물 반응기 단백질 생산을 체계적으로 최적화합니다. 우리의 결과는 유연한 소프트웨어가 기존 하드웨어에 힘을 실어 새로운 유형과 규모의 실험을 가능하게 하고 생물 제조에서 기초 생물학에 이르는 영역에 힘을 실어줄 수 있음을 보여줍니다.

### Automated Rational Strain Construction Based on High-Throughput Conjugation

        https://pubs.acs.org/doi/full/10.1021/acssynbio.0c00599
        
        분자 복제는 DNA 조립과 표적 숙주에서의 발현으로 구성되기 때문에 합성 생물학의 핵심입니다. 그러나 현재 복제는 자동화의 이점이 큰 수동적이고 시간 소모적이며 반복적인 프로세스인 경우가 가장 많습니다. 완전한 합리적인 클로닝 절차의 자동화, 즉 DNA 생성에서 표적 숙주에서의 발현까지의 자동화에는 다양한 작업과 기계의 통합이 포함됩니다. 이러한 워크플로우의 예는 드물고, 특히 설계가 합리적이고( 즉 , DNA 서열 설계가 고정되어 있으며 무작위 라이브러리를 기반으로 하지 않음) 표적 숙주가 유전적으로 다루기 쉽지 않은 경우( 예:, 열충격 변형에 민감하지 않음). 이 연구에서는 플라스미드의 합리적인 구성과 생명공학 플랫폼 유기체인 코리네박테리움 글루타미쿰 으로의 후속 컨쥬게이티브 전송을 위한 자동화된 워크플로가 제시됩니다. 전체 작업 흐름에는 맞춤형 소프트웨어 도구가 수반됩니다. 응용 예로서 조절자 Lrp를 기반으로 합리적으로 설계된 전사 인자-바이오 센서 라이브러리를 구축하고 특성화했습니다. 동적 범위가 개선된 센서를 얻었고 스크리닝에서 얻은 통찰력은 C. 글루타미쿰 Lrp의 이중 조절기 기능에 대한 증거를 제공했습니다.

### 자동화 코드 참고할만한 저널

-   https://journal.code4lib.org/

## **DNA-BOT: a low-cost, automated DNA assembly platform for synthetic biology**

    다중 부분 DNA 조립은 합성 및 분자 생물학의 많은 프로젝트에서 물리적 출발점입니다. 광범위한 DNA 구조 라이브러리를 구축하여 유전자 설계 공간을 탐색하는 능력은 프로그래밍된 생물학적 시스템을 만드는 데 필수적입니다. 합성 생물학 커뮤니티에서 채택된 여러 DNA 조립 방법 및 표준으로 인해 DNA 조립 프로세스의 자동화가 이제 큰 관심을 받고 있습니다. 자동화를 통해 접근 가능한 디자인 공간을 늘리는 동시에 연구자의 시간을 덜 사용하여 더 큰 빌드를 만들 수 있습니다. 그러나 이러한 이점은 현재 장비와 소모품 모두에 높은 비용을 초래합니다. 여기에서는 DNA-BOT(OpenTrons)의 BASIC을 사용하여 저비용 DNA 어셈블리를 도입하여 이러한 제한 사항을 해결합니다. 이 목적을 위해, 우리는 오픈 소스 소프트웨어 패키지를 개발하고 10개의 유전 부분으로 구성된 88개의 구성을 동시에 조립하고 3개 유전자 오페론에 대한 프로모터, 리보솜 결합 부위 및 유전자 순서 설계 공간을 평가하여 DNA-BOT의 성능을 시연했습니다. 88개의 모든 구성은 구성당 $1.50–$5.50의 소모품 비용으로 높은 정확도로 조립되었습니다. 이것은 DNA-BOT의 효율성, 정확성 및 경제성을 보여주며 대부분의 실험실에서 접근 가능하고 자동화된 DNA 조립을 민주화합니다.
