---
title: "biosensors"
author: "Haseong"
date: "05/03/2023"
filters: 
  - lightbox
lightbox: auto
categories:
  - syntheic biology
  - biosensors
---

# Biosensors

-   Biosensors and Machine Learning for Enhanced Detection, Stratification, and Classification of Cells: A Review

<!-- -->

    Biological cells, by definition, are the basic units which contain the fundamental molecules of life of which all living things are composed. Understanding how they function and differentiating cells from one another therefore is of paramount importance for disease diagnostics as well as therapeutics. Sensors focusing on the detection and stratification of cells have gained popularity as technological advancements have allowed for the miniaturization of various components inching us closer to Point-of-Care (POC) solutions with each passing day. Furthermore, Machine Learning has allowed for enhancement in analytical capabilities of these various biosensing modalities, especially the challenging task of classification of cells into various categories using a data-driven approach rather than physics-driven. In this review, we provide an account of how Machine Learning has been applied explicitly to sensors that detect and classify cells. We also provide a comparison of how different sensing modalities and algorithms affect the classifier accuracy and the dataset size required.

    정의에 따르면 생물학적 세포는 모든 생물을 구성하는 생명의 기본 분자를 포함하는 기본 단위입니다. 따라서 세포가 어떻게 기능하고 세포를 구별하는지 이해하는 것은 질병 진단 및 치료에 있어 가장 중요합니다. 기술 발전으로 다양한 구성 요소의 소형화가 가능해짐에 따라 세포 감지 및 층화에 초점을 맞춘 센서가 인기를 얻었고, 날이 갈수록 POC(Point-of-Care) 솔루션에 가까워졌습니다. 또한 머신 러닝은 이러한 다양한 바이오센싱 양식의 분석 기능, 특히 물리학 중심이 아닌 데이터 중심 접근 방식을 사용하여 세포를 다양한 범주로 분류하는 어려운 작업을 향상시킬 수 있습니다. 이 리뷰에서는 기계 학습이 세포를 감지하고 분류하는 센서에 어떻게 명시적으로 적용되었는지에 대한 설명을 제공합니다. 또한 서로 다른 감지 양식 및 알고리즘이 분류기 정확도 및 필요한 데이터 세트 크기에 미치는 영향에 대한 비교도 제공합니다.

-   
