---
title: "synthetic biology"
author: "Haseong"
date: "05/03/2023"
filters: 
  - lightbox
lightbox: auto
categories:
  - syntheic biology
  - biofoundry
  - automation
---

# Synthetic biology

## 독일

-   https://www.sciencedirect.com/science/article/pii/S2665906921000179#bib5
-   Synthetic biology landscape and community in Germany

<!-- -->

    Despite its start in the early 2000s, synthetic biology is still overall perceived as a young discipline. In some countries, such as the US, synthetic biology is academically and industrially established, while in others, including Germany, it is still an upcoming field of research. Issues with funding schemes, commercial translation of technologies, public perception, and regulations need to be addressed to establish synthetic biology as a key discipline of the 21st century. This perspective article reviews the German and European synthetic biology landscape and how the German Association for Synthetic Biology (GASB) is addressing the above-mentioned challenges with its events and community-building activities.

    2000년대 초반에 시작되었음에도 불구하고 합성 생물학은 여전히 전반적으로 젊은 분야로 인식되고 있습니다. 미국과 같은 일부 국가에서는 합성생물학이 학문적, 산업적으로 확립되어 있는 반면, 독일을 포함한 다른 국가에서는 여전히 향후 연구 분야입니다. 자금 조달 계획, 기술의 상업적 번역, 대중의 인식 및 규정과 관련된 문제를 해결하여 합성 생물학을 21세기의 핵심 분야로 확립해야 합니다. 이 관점 기사는 독일과 유럽의 합성 생물학 환경과 GASB(독일 합성 생물학 협회)가 이벤트 및 커뮤니티 구축 활동을 통해 위에서 언급한 문제를 해결하는 방법을 검토합니다.

# 영국

-   Synthetic biology landscape in the UK (2022)

-   https://www.sciencedirect.com/science/article/pii/S2665906922000071?via%3Dihub

<!-- -->

    영국은 활기차고 다양한 합성 생물학 커뮤니티의 본거지입니다. 연구 혁신 및 기술 상용화에서 많은 성공을 거둔 것은 헌신적인 학자, 투자자, 산업 리더십 및 정책 입안자의 강력한 기반에 기인할 수 있습니다. 여기에서는 이러한 성공의 핵심이 된 네트워크를 구성하는 조직과 커뮤니티의 다양한 수준에서 수행하는 역할에 대한 개요를 제공합니다. 우리는 영국의 합성 생물학에 대한 간략한 역사로 시작하여 영국의 활발한 학생 및 기업가 정신 현장과 연구 센터에 특히 중점을 두고 설립된 사회 및 기관의 진행 상황을 설명하는 것으로 계속합니다. 그런 다음 영국의 성장하는 바이오 경제를 맥락화하여 계획된 혁신에 대한 정부의 궤적과 이것이 연구 번역과 어떻게 일치하는지 자세히 설명합니다. 연구자를 위한 상업화의 길은 합성 생물학 및 그 번역 분야의 세계적인 선두 주자인 미국의 경로와 비교하여 영국을 전 세계적으로 차별화하는 측면을 강조합니다. 마지막으로, 우리는 현재의 진행 속도와 커뮤니티의 상태에 대한 밝은 전망으로 결론을 내립니다.

# 유럽

-   Synthetic biology in Europe: current community landscape and future perspectives (2022)

-   https://www.sciencedirect.com/science/article/pii/S2665906922000083?via%3Dihub

<!-- -->

    합성 생물학은 과학자들의 상상력을 사로 잡았습니다. 그것은 사회가 직면하고 있는 몇 가지 큰 도전, 즉 기후 위기 악화, 계속 증가하는 인구를 위한 식량 공급 부족, 지속되는 많은 전염병 및 유전 질환에 대한 해답을 약속합니다. 많은 도전 과제가 해결되지 않은 채로 남아 있지만, 창립 이래 거의 20년이 지난 후 공학 생물학에 의해 만들어진 많은 제품이 대중에게 다가가기 시작했습니다. 유럽의 과학자들과 기업가들은 합성 생물학의 약속을 이행하는 데 참여해 왔습니다. 유럽 합성 생물학 협회(EUSynBioS)와 같은 협회는 이 분야의 발전을 전파하고 같은 생각을 가진 사람들을 연결하며 과학 발전을 촉진하는 데 핵심적인 역할을 합니다. 이 관점 기사에서는 유럽 합성 생물학 커뮤니티의 현재 환경을 검토하고 관련 학술 연구 및 산업의 현황에 대해 논의합니다. 또한 EUSynBioS가 대륙 전역의 전문가들 사이에 다리를 놓는 데 어떻게 도움이 되었는지에 대해서도 논의합니다.

# 중국

-   Synthetic biology in China: Review and prospects

-   https://www.sciengine.com/SSV/doi/10.1360/SSV-2019-0299;JSESSIONID=7441bb8d-8f65-48cc-9d6d-453d21ae822d

<!-- -->

    합성 생물학은 신흥 과학이자 전형적인 융합 기술입니다. 시스템 생물학을 기반으로 공학 과학의 원리를 통합하고 상향식 전략을 채택하여 새로운 생물학적 시스템을 설계 및 구축하거나 기존 생물학적 시스템을 재 설계하여 생명의 메커니즘을 밝히고 새로운 세대의 생명 공학을 구축하는 것을 목표로합니다. 초기에 중국 과학자들은 기능성 단백질 (소 인슐린)과 리보 핵산 (효모 알라닌 tRNA)을 인위적으로 합성 한 최초의 과학자들이었습니다. 최근 몇 년 동안 그들은 염색체 합성 및 염색체 공학, 게놈 편집, 생물학적 섀시 구성, 정량 공학 생물학, 생물학적 부분 및 유전자 회로 공학, 천연 제품 및 유기 화학 제품의 합성 대사 및 구현 기술(예: 게놈 편집 및 컴퓨터 시뮬레이션)에 종사했으며 일련의 중요한 발견과 혁신적인 성과를 거두었습니다. 이로 인해 중국 과학자들은 국제 합성 생물학 컨소시엄에서 중요한 역할을 맡았습니다. 중국의 70 년 과학 기술 발전을 검토 할 때까지이 기사는 개척자를 기념하고 현장의 초기 경력 학자들에게 영감을 불어 넣는 동시에 경험과 교훈을 논의하고 미래의 우선 순위와 기회를 식별하는 것입니다. 오늘날 합성 생물학은 세계에서 호황을 누리고 있으며 중국 과학자들은 이에 중요한 역할을 하게 되어 기쁩니다.
