---
site: bookdown::bookdown_site
mainfont: Nanum Myeongjo
documentclass: book
bibliography:
- book.bib
- packages.bib
biblio-style: apalike
link-citations: yes
description: This is Haseong's home.
output:
  html_document:
    df_print: paged
---

# Intro

-   김하성 (Haseong Kim)
-   한국생명공학연구원 (KRIBB) 합성생물학연구소 책임연구원 (2012 \~) <!-- * 과학기술연합대학원대학교 (UST) 생명공학과 부교수 (2021 ~)  --> <!-- * 한국과학기술원 (KAIST) 바이오및뇌공학과 겸직교수 (2022 ~)  --> <!-- * 외교부 과학기술외교자문위원 (2022 ~)  --> <!-- * 과학기술정보통신부 장관표창 (2021)   -->

# Lectures

-   \[2022년 KRIBB 연구데이터 분석과정\] [R을 이용한 생명데이터 분석 full](https://greendaygh.github.io/kribbr2022/)
-   \[2022년 1학기 UST 대학원 전공강의\] \[시스템합성생물학\]
-   \[2021년 2학기 UST 대학원 전공강의\] \[현장연구A\] <!-- (https://greendaygh.github.io/fieldresearch2021-2/) -->
-   \[2021년 KRIBB 연구데이터 분석과정\] [R을 이용한 생명데이터 분석 short](https://greendaygh.github.io/kribbr2021/)
-   \[2021년 1학기 UST 대학원 전공강의\] \[현장연구E\] <!-- (https://greendaygh.github.io/researchE2021/) -->
-   \[2021년 1학기 UST 대학원 일반강의\] [데이터 사이언스를 위한 R 프로그래밍](https://greendaygh.github.io/Rprog2021/)
-   \[2020년 KRIBB 연구데이터 분석과정\] [R을 이용한 생명데이터 분석](https://greendaygh.github.io/KRIBBR2020/)
-   \[2020년 2학기 UST 대학원 일반강의\] [R로 배우는 기초통계](https://greendaygh.github.io/Rstat2020/)
-   \[2020년 1학기 UST 대학원 일반강의\] [R 프로그래밍과 데이터분석](https://greendaygh.github.io/Rprog2020/)
-   \[2019년 12월 생물공학회 교육 워크샵\] [기계학습 x 생물공학](https://github.com/greendaygh/bioengml)
-   \[2019년 2학기 UST 대학원 일반강의\] [R로 배우는 기초통계](https://greendaygh.github.io/Rstat2019/)
-   \[2019년 1학기 UST 대학원 일반강의\] [R 프로그래밍과 데이터분석](https://greendaygh.github.io/Rprog2019/)

# Media

-   \[2022-11-30\] \[동아사이언스\] [코로나 파괴 인공효소 만드는 '합성생물학' 혁신 '눈앞'](https://www.dongascience.com/news.php?idx=57241)
-   \[2022-07-25\] \[바이오인프로\] [차세대 유전체 합성 연구개발 동향 및 전망](https://www.bioin.or.kr/board.do?num=317494&cmd=view&bid=report)
-   \[2022-07-22\] \[2022 바이오 미래유망기술 시리즈 플랫폼바이오\] [레드·그린·화이트바이오 혁신의 공통 엔진인 플랫폼바이오](https://youtu.be/HQwqaGc4Zg4)
-   \[2021-10-12\] \[바이오인와치\] [제조업을 혁신할 자연지향설계(Nature Co-Design) 시대 도래](https://www.bioin.or.kr/board.do?num=311389&cmd=view&bid=issue)
-   \[2021-04-31\] \[한국과총\] [인류 번영을 위한 혁신기술, 합성생물학](http://ebook.kofst.or.kr/book/202104/#page=71)
-   \[2021-02-24\] \[한국경제, 유료\] [생물학의 산업적 활용을 촉진하는 바이오파운드리 구축 필요](https://www.hankyung.com/it/article/202102096254i)
-   \[2020-12-17\] \[전자신문 외 15건\] [AI 만난 미생물 바이오센서, 유해물질 95% 식별](https://www.fnnews.com/news/202012161243526206)
-   \[2020-7-30\] \[한국생물공학회\] [딥러닝(CNN)기반 DNA 서열분석 가이드](http://www.btnews.or.kr/bbs/board.php?bo_table=bt_news&wr_id=342)
-   \[2020-5-1\] \[바이오리소스 인사이트 Vol5\] [합성생물학과 생명연구자원](https://www.kobis.re.kr/go_document?page_name=publication_bio_insight)
-   \[2020-2-3\] \[바이오인에세이 감수\] [2020 바이오미래기유망기술의 이야기-바이오파운드리](https://www.bioin.or.kr/board.do?num=304334&cmd=view&bid=essay)
-   \[2020-2-11\] \[바이오인 기술 추천 및 기초자료 작성\] [2020년 10대 바이오 미래유망기술 바이오파운드리](https://www.bioin.or.kr/board.do?num=293995&cmd=view&bid=essay&cPage=1&cate1=all&cate2=all2)
-   \[2019-12-31\] \[바이오인에세이 감수\] [2019 바이오미래기유망기술의 이야기-유전자회로 공정 예측기술](https://www.bioin.or.kr/board.do?num=292912&cmd=view&bid=essay)
-   \[2019-12-04\] \[바이오인프로\] [바이오파운드리 동향](https://www.bioin.or.kr/board.do?num=292266&cmd=view&bid=report&cPage=1&cate1=all&cate2=all2)
-   \[2019-09-17\] \[한국경제\] [자동화 로봇 기술 덕분에 10년 걸리던 표현형 데이터 수일 內 확보](https://www.hankyung.com/it/article/2019091732761)
-   \[2016-09-20\] \[보도자료\] [저비용·고효율 맞춤형 미생물 검색 형광 플랫폼 개발](https://www.bioin.or.kr/board.do?num=263870&cmd=view&bid=research)
-   \[2015-07-27\] \[바이오인프로\] [합성생물학의 최신 연구동향](https://www.bioin.or.kr/board.do?num=253760&cmd=view&bid=report)
-   \[2013-02-03\] \[지능형합성생물학연구단\] [합성생물학 부품 표준화 및 설계 정형화에 관한 연구 동향](http://www.syntheticbiology.or.kr/board.php?db=sub0302&no=44&c=view&page=8)

# Selected publications

[Full paper list](https://oak.kribb.re.kr/researcher-profile?ep=137&type=all&sort_by=dc.date.issued_dt&order=DESC)

**Haseong Kim** , Wonjae Seong, Eugene Rha, Hyewon Lee, Seong Keun Kim, Kil Koang Kwon, K H Park, Dae-Hee Lee, Seung Goo Lee (2020) "Machine learning linked evolutionary biosensor array for highly sensitive and specific molecular identification" Biosens Bioelectron. 170(0) : 112670-112670.

**H. Kim** "AI, big data, and robots for the evolution of biotechnology" GENOM INFORMAT. 17(4) : e44-e44, 2019

SK Kim\*, **H. Kim\***, WC Ahn, KH Park, E Woo, DH Lee, and SG Lee, Efficient Transcriptional Gene Repression by Type V-A CRISPR-Cpf1 from Eubacterium eligens, 10.1021/acssynbio.6b00368, 2017

**H. Kim\***, E. Rha\*, W. Seong, SJ Yeom, DH Lee, S G Lee, A cell-cell communication-based screening system for novel microbes with target enzyme activities, ACS Synthetic Biology, DOI: 10.1021/acssynbio.5b00287, 2016

**H. Kim**, KK Kwon, W. Seong, SG Lee, Multi-Enzyme Screening Using a High-throughput Genetic Enzyme Screening System, The Journal of Visualized Experiments, (114), e54059, 2016

Y J Kim\*, **H. Kim\***, S H Kim, E Rha, S-L Choi, S J Yeom, H S Kim, S G Lee, Improved metagenome screening efficiency by random insertion of T7 promoters J BIOTECHNOL, 230(0) : 47-53, 2016

SL Choi, E Rha, SJ Lee, **H. Kim**, G Kwon, YS Jeong, YH Rhee, JJ Song, HS Kim, SG Lee, Towards a Generalized and High-throughput Enzyme Screening System Based on Artificial Genetic Circuits, ACS Synthetic Biology, 3(3), 2014

**H. Kim**, T. Park, and E. Gelenbe, Identifying Disease Candidate Genes via Large-scale Gene Network Analysis, International Journal of Data Mining and Bioinformatics, 10(2), 2014

**H. Kim**, Modelling and analysis of gene regulatory networks based on the G-network, International Journal of Advanced Intelligence Paradigms, 6(1), 2014
