name: quarto-setup

on:
  push:

jobs:
  quarto-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
          
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
